### ISSUE TITLE
Library doesn't build w/ ICC on OSX

### ISSUE THREAD

**Issue by amanoel** [JuliaLang/libosxunwind#2]
Following the discussion at https://github.com/JuliaLang/julia/issues/9145, the .s extension must be capitalized (and the Makefile changed accordingly) in order for ICC to be able to build it on OSX.
I'm not sure if doing this wouldn't break the build on other OSes though...

**Comment by tkelman** [comment]
That would surprise me. We only use this library on OSX anyway.

**Comment by amanoel** [comment]
Hmm, if it's only used in OSX, wouldn't it be a good idea to always use the system-provided library?
I've tried using the USE_SYSTEM_LIBUNWIND=1 flag and apparently it's also a good way to circumvent this.

**Comment by tkelman** [comment]
You'd have to ask @Keno exactly what purpose this serves. I dunno the difference `USE_SYSTEM_LIBUNWIND` would make in practice.

**Comment by Keno** [comment]
You'd get less accurate profiles. The modifications in this library have some heuristics that allow it to unwind from non-callsite locations.

**Comment by nolta** [comment]
Another option would be to add `-x assembler-with-cpp` to `SFLAGS`.

Tried to fix this, but i don't have permission.

**Comment by amanoel** [comment]
Can confirm `make CC="icc" SFLAGS="$SFLAGS -x assembler-with-cpp"` works!
