### ISSUE TITLE
Julia build fails on OS X with latest master

### ISSUE THREAD

**Issue by protogeezer** [JuliaLang/libosxunwind#5]
_From @protogeezer on February 26, 2016 16:55_

build with fresh git clone fails while building libosxunwind...
# 

```
et-imac-retina:julia sjbespa$ ./clone-julia julia-0.5-master
Cloning into 'julia-0.5-master'...
remote: Counting objects: 169353, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 169353 (delta 4), reused 0 (delta 0), pack-reused 169341
Receiving objects: 100% (169353/169353), 97.26 MiB | 8.92 MiB/s, done.
Resolving deltas: 100% (129141/129141), done.
Checking connectivity... done.

et-imac-retina:julia sjbespa$ cd julia-0.5-master

et-imac-retina:julia-0.5-master sjbespa$ make -j4
Creating usr/etc/julia/juliarc.jl
Copying in usr/share/doc/julia/examples
Copying in usr/share/man/man1/julia.1
...
patching file TESTS/bug_1315_double.c
patching file TESTS/bug_1315_single.c
make[2]: Circular src/libuwind.cxx <- src/libuwind.cxx.o dependency dropped.
clang: error: no such file or directory: 'libosxunwind.a'
make[2]: *** [libosxunwind.dylib] Error 1
make[2]: *** Waiting for unfinished jobs....
```

_Copied from original issue: JuliaLang/julia#15255_

**Comment by protogeezer** [comment]
_From @vtjnash on February 26, 2016 18:17_

iirc, this indicates an issue with your path, such as having a space in it

**Comment by protogeezer** [comment]
The path is:
et-imac-retina:julia-0.5-master sjbespa$ pwd
/Users/sjbespa/work/julia/julia-0.5-master
No spaces; is there something else going on with the path?

BTW, I built from the master again, and still got the error about the circular dependency, but it didn't crash:

patching file TESTS/bug_1315_double.c
patching file TESTS/bug_1315_single.c
make[2]: Circular src/libuwind.cxx <- src/libuwind.cxx.o dependency dropped.
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libosxunwind.a(Unwind-sjlj.c.o) has no symbols
clang: warning: optimization flag '-finline-functions' is not supported

so, since it's crashed twice and made it through once, perhaps there is a problem with the -j4 switch?

**Comment by protogeezer** [comment]
_From @ViralBShah on February 27, 2016 3:24_

Yes, the -j 4 switch is problematic. You can use it, but there will be a dependency problem at some stage, which can be cleaned up with a simple make (without -j).

**Comment by protogeezer** [comment]
_From @ViralBShah on February 27, 2016 3:25_

If make (without -j) works, this issue should be retitled.

**Comment by protogeezer** [comment]
_From @tkelman on February 27, 2016 3:46_

And potentially moved to https://github.com/JuliaLang/libosxunwind, if that's the only place where parallel make can be repeatably demonstrated to cause problems right now.

**Comment by ViralBShah** [comment]
@yuyichao Given that we have our own libunwind now, does it make sense to merge the osx stuff in there as well?

**Comment by yuyichao** [comment]
It's still unclear what the plan is but I think it makes sense to merge the two and try to upstream the patches, whoever the upstream end up being....

**Comment by tkelman** [comment]
and as I understand it, apple's libunwind (where this code came from originally) is now a part of llvm proper

**Comment by protogeezer** [comment]
What's going on with this bug? A slightly different question would be: what are the current plans for switching to cmake - which understands complex dependencies and parallel builds...

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/pull/11754

**Comment by vtjnash** [comment]
fixed by https://github.com/JuliaLang/libosxunwind/pull/14
